# Use the official Node.js image from DockerHub
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app/frontend

# Copy package.json and package-lock.json
COPY ./package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the frontend files
COPY ./ ./

# If DEV=true, we'll run the React development server
CMD npm start
