# Use the official Node.js image from DockerHub
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /code/frontend

# Copy package.json and package-lock.json
COPY ./package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the frontend files
COPY ./ ./

# If DEV is false, create a production build
CMD npm run build

COPY ./build ./build