version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app/frontend

  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app/backend
