# Use the official Python image from DockerHub
FROM python:3.12-alpine

# Install the dependencies required to build the Python packages
RUN apk update && apk add --no-cache \
    build-base \
    libffi-dev \
    openssl-dev \
    rust \
    cargo

# Set the working directory inside the container
WORKDIR /code/backend

# Depending on the ARG value, copy the appropriate requirements file
COPY ./requirements-dev.txt ./requirements.txt

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy the content of the backend directory to the working directory
COPY ./app /code/backend/app
COPY ./alembic.ini /code/backend/alembic.ini
COPY ./alembic /code/backend/alembic
COPY ./start.sh /code/backend/start.sh
COPY ./wait_for_db.py /code/backend/wait_for_db.py

RUN chmod +x /code/backend/start.sh

# Command to run the application using Uvicorn
CMD /code/backend/start.sh
